/*! Copyright 2026 Adobe
All Rights Reserved. */
import{a as x,f as y,h as O}from"./network-error.js";import"@dropins/tools/recaptcha.js";import{events as p}from"@dropins/tools/event-bus.js";import{merge as G}from"@dropins/tools/lib.js";import{c as k,f as S,C as $,d as U,e as F,L as v}from"./getAdobeCommerceOptimizerData.js";import{CUSTOMER_INFORMATION_FRAGMENT as C}from"../fragments.js";import{p as J,E as A}from"./acdl.js";import{s as D}from"./setReCaptchaToken.js";const H=t=>{var c,o,r,d,i,m,e,g,l,_,s,n,h,E,u,M;const a={email:((o=(c=t==null?void 0:t.data)==null?void 0:c.customer)==null?void 0:o.email)??"",firstName:((d=(r=t==null?void 0:t.data)==null?void 0:r.customer)==null?void 0:d.firstname)??"",lastName:((m=(i=t==null?void 0:t.data)==null?void 0:i.customer)==null?void 0:m.lastname)??"",groupUid:((l=(g=(e=t==null?void 0:t.data)==null?void 0:e.customer)==null?void 0:g.group)==null?void 0:l.uid)??"",allowRemoteShoppingAssistance:(s=(_=t==null?void 0:t.data)==null?void 0:_.customer)==null?void 0:s.allow_remote_shopping_assistance};return G(a,(M=(u=(E=(h=(n=k)==null?void 0:n.getConfig())==null?void 0:h.models)==null?void 0:E.CustomerModel)==null?void 0:u.transformer)==null?void 0:M.call(u,t.data))},K=`
  query GET_CUSTOMER_DATA {
    customer {
      ...CUSTOMER_INFORMATION_FRAGMENT
    }
  }
  ${C}
`,Q=async t=>{if(t){const{authHeaderConfig:a}=k.getConfig();x(a.header,a.tokenPrefix?`${a.tokenPrefix} ${t}`:t)}return await y(K,{method:"GET",cache:"force-cache"}).then(a=>H(a)).catch(O)},W=`
  mutation GET_CUSTOMER_TOKEN($email: String!, $password: String!) {
    generateCustomerToken(email: $email, password: $password) {
      token
    }
  }
`,R=t=>{if(!t||typeof t!="string")return null;try{const a=t.split(".");if(a.length!==3)return console.error("[decodeJwtToken] Invalid JWT format: expected 3 parts"),null;const o=a[1].replace(/-/g,"+").replace(/_/g,"/"),r=o.padEnd(o.length+(4-o.length%4)%4,"="),d=atob(r);return JSON.parse(d)}catch(a){return console.error("[decodeJwtToken] Failed to decode JWT:",a),null}},j=t=>{const a=R(t);return a?typeof a.admin_id=="number"&&a.admin_id>0:!1},q=(t,a)=>{const c=R(t);if(c&&typeof c.exp=="number"&&c.exp>0){const o=Math.floor(Date.now()/1e3);return`Max-Age=${Math.max(0,c.exp-o)}`}return a},b=async({email:t,password:a,translations:c,onErrorCallback:o,handleSetInLineAlertProps:r,apiErrorMessageOverride:d})=>{var h,E,u,M,N;await D();const i=await y(W,{method:"POST",variables:{email:t,password:a}}).catch(O);if(!((E=(h=i==null?void 0:i.data)==null?void 0:h.generateCustomerToken)!=null&&E.token)){const f=c.customerTokenErrorMessage,T=i!=null&&i.errors?i.errors[0].message:f,w=d??T;return o==null||o(T),r==null||r({type:"error",text:w}),{errorMessage:T,displayErrorMessage:w,userName:"",userEmail:""}}const m=(M=(u=i==null?void 0:i.data)==null?void 0:u.generateCustomerToken)==null?void 0:M.token,e=await Q(m),g=e==null?void 0:e.firstName,l=(e==null?void 0:e.lastName)??"",_=e==null?void 0:e.email;if(!g||!_){const f=c.customerTokenErrorMessage,T=d??f;return o==null||o(f),r==null||r({type:"error",text:T}),{errorMessage:f,displayErrorMessage:T,userName:"",userEmail:""}}const s=await S(),n=v.includes(window.location.hostname)?"":"Secure";if(document.cookie=`${$.auth_dropin_firstname}=${g}; path=/; ${s}; ${n};`,document.cookie=`${$.auth_dropin_lastname}=${l}; path=/; ${s}; ${n};`,document.cookie=`${$.auth_dropin_user_token}=${m}; path=/; ${s}; ${n};`,j(m)){const f=q(m,s);document.cookie=`${$.auth_dropin_admin_session}=true; path=/; ${f}; SameSite=Lax; ${n};`}else U($.auth_dropin_admin_session);return await F(m?e==null?void 0:e.groupUid:void 0),p.emit("authenticated",!!m),J((N=A)==null?void 0:N.SIGN_IN,{...e}),{errorMessage:"",displayErrorMessage:"",userName:g,userEmail:_}};export{b as a,Q as g};
//# sourceMappingURL=getCustomerToken.js.map
