/*! Copyright 2026 Adobe
All Rights Reserved. */
import{a as R,f as O,h as y}from"./network-error.js";import"@dropins/tools/recaptcha.js";import{events as G}from"@dropins/tools/event-bus.js";import{merge as S}from"@dropins/tools/lib.js";import{c as k,f as U,C as M,d as x,e as F,L as p}from"./getAdobeCommerceOptimizerData.js";import{CUSTOMER_INFORMATION_FRAGMENT as v}from"../fragments.js";import{p as C,E as J}from"./acdl.js";import{s as A}from"./setReCaptchaToken.js";const D=t=>{var n,o,c,r,i,m,a,g,T,_,d,u,h,E,s,$;const e={email:((o=(n=t==null?void 0:t.data)==null?void 0:n.customer)==null?void 0:o.email)??"",firstName:((r=(c=t==null?void 0:t.data)==null?void 0:c.customer)==null?void 0:r.firstname)??"",lastName:((m=(i=t==null?void 0:t.data)==null?void 0:i.customer)==null?void 0:m.lastname)??"",groupUid:((T=(g=(a=t==null?void 0:t.data)==null?void 0:a.customer)==null?void 0:g.group)==null?void 0:T.uid)??"",allowRemoteShoppingAssistance:(d=(_=t==null?void 0:t.data)==null?void 0:_.customer)==null?void 0:d.allow_remote_shopping_assistance};return S(e,($=(s=(E=(h=(u=k)==null?void 0:u.getConfig())==null?void 0:h.models)==null?void 0:E.CustomerModel)==null?void 0:s.transformer)==null?void 0:$.call(s,t.data))},H=`
  query GET_CUSTOMER_DATA {
    customer {
      ...CUSTOMER_INFORMATION_FRAGMENT
    }
  }
  ${v}
`,K=async t=>{if(t){const{authHeaderConfig:e}=k.getConfig();R(e.header,e.tokenPrefix?`${e.tokenPrefix} ${t}`:t)}return await O(H,{method:"GET",cache:"force-cache"}).then(e=>D(e)).catch(y)},Q=`
  mutation GET_CUSTOMER_TOKEN($email: String!, $password: String!) {
    generateCustomerToken(email: $email, password: $password) {
      token
    }
  }
`,W=t=>{if(!t||typeof t!="string")return null;try{const e=t.split(".");if(e.length!==3)return console.error("[decodeJwtToken] Invalid JWT format: expected 3 parts"),null;const o=e[1].replace(/-/g,"+").replace(/_/g,"/"),c=o.padEnd(o.length+(4-o.length%4)%4,"="),r=atob(c);return JSON.parse(r)}catch(e){return console.error("[decodeJwtToken] Failed to decode JWT:",e),null}},j=t=>!!W(t),L=async({email:t,password:e,translations:n,onErrorCallback:o,handleSetInLineAlertProps:c,apiErrorMessageOverride:r})=>{var h,E,s,$,l;await A();const i=await O(Q,{method:"POST",variables:{email:t,password:e}}).catch(y);if(!((E=(h=i==null?void 0:i.data)==null?void 0:h.generateCustomerToken)!=null&&E.token)){const N=n.customerTokenErrorMessage,f=i!=null&&i.errors?i.errors[0].message:N,w=r??f;return o==null||o(f),c==null||c({type:"error",text:w}),{errorMessage:f,displayErrorMessage:w,userName:"",userEmail:""}}const m=($=(s=i==null?void 0:i.data)==null?void 0:s.generateCustomerToken)==null?void 0:$.token,a=await K(m),g=a==null?void 0:a.firstName,T=a==null?void 0:a.lastName,_=a==null?void 0:a.email;if(!g||!T||!_){const N=n.customerTokenErrorMessage,f=r??N;return o==null||o(N),c==null||c({type:"error",text:f}),{errorMessage:N,displayErrorMessage:f,userName:"",userEmail:""}}const d=await U(),u=p.includes(window.location.hostname)?"":"Secure";return document.cookie=`${M.auth_dropin_firstname}=${g}; path=/; ${d}; ${u};`,document.cookie=`${M.auth_dropin_lastname}=${T}; path=/; ${d}; ${u};`,document.cookie=`${M.auth_dropin_user_token}=${m}; path=/; ${d}; ${u};`,j(m)?document.cookie=`${M.auth_dropin_admin_session}=true; path=/; ${d}; SameSite=Lax; ${u};`:x(M.auth_dropin_admin_session),await F(m?a==null?void 0:a.groupUid:void 0),G.emit("authenticated",!!m),C((l=J)==null?void 0:l.SIGN_IN,{...a}),{errorMessage:"",displayErrorMessage:"",userName:g,userEmail:_}};export{L as a,K as g};
//# sourceMappingURL=getCustomerToken.js.map
