/*! Copyright 2026 Adobe
All Rights Reserved. */
import{a as k,f as w,h as O}from"./network-error.js";import"@dropins/tools/recaptcha.js";import{events as R}from"@dropins/tools/event-bus.js";import{merge as G}from"@dropins/tools/lib.js";import{c as y,f as S,C as $,d as C,e as U,L as x}from"./getAdobeCommerceOptimizerData.js";import{CUSTOMER_INFORMATION_FRAGMENT as F}from"../fragments.js";import{p,E as v}from"./acdl.js";import{s as J}from"./setReCaptchaToken.js";const A=t=>{var s,e,r,m,o,c,i,u,T,g,f,_,h,E,d,M;const a={email:((e=(s=t==null?void 0:t.data)==null?void 0:s.customer)==null?void 0:e.email)??"",firstName:((m=(r=t==null?void 0:t.data)==null?void 0:r.customer)==null?void 0:m.firstname)??"",lastName:((c=(o=t==null?void 0:t.data)==null?void 0:o.customer)==null?void 0:c.lastname)??"",groupUid:((T=(u=(i=t==null?void 0:t.data)==null?void 0:i.customer)==null?void 0:u.group)==null?void 0:T.uid)??"",allowRemoteShoppingAssistance:(f=(g=t==null?void 0:t.data)==null?void 0:g.customer)==null?void 0:f.allow_remote_shopping_assistance};return G(a,(M=(d=(E=(h=(_=y)==null?void 0:_.getConfig())==null?void 0:h.models)==null?void 0:E.CustomerModel)==null?void 0:d.transformer)==null?void 0:M.call(d,t.data))},D=`
  query GET_CUSTOMER_DATA {
    customer {
      ...CUSTOMER_INFORMATION_FRAGMENT
    }
  }
  ${F}
`,H=async t=>{if(t){const{authHeaderConfig:a}=y.getConfig();k(a.header,a.tokenPrefix?`${a.tokenPrefix} ${t}`:t)}return await w(D,{method:"GET",cache:"force-cache"}).then(a=>A(a)).catch(O)},K=`
  mutation GET_CUSTOMER_TOKEN($email: String!, $password: String!) {
    generateCustomerToken(email: $email, password: $password) {
      token
    }
  }
`,Q=t=>{if(!t||typeof t!="string")return null;try{const a=t.split(".");if(a.length!==3)return console.error("[decodeJwtToken] Invalid JWT format: expected 3 parts"),null;const e=a[1].replace(/-/g,"+").replace(/_/g,"/"),r=e.padEnd(e.length+(4-e.length%4)%4,"="),m=atob(r);return JSON.parse(m)}catch(a){return console.error("[decodeJwtToken] Failed to decode JWT:",a),null}},W=t=>!!Q(t),Z=async({email:t,password:a,translations:s,onErrorCallback:e,handleSetInLineAlertProps:r,apiErrorMessageOverride:m})=>{var _,h,E,d,M;await J();const o=await w(K,{method:"POST",variables:{email:t,password:a}}).catch(O);if(!((h=(_=o==null?void 0:o.data)==null?void 0:_.generateCustomerToken)!=null&&h.token)){const N=s.customerTokenErrorMessage,n=o!=null&&o.errors?o.errors[0].message:N,l=m??n;return e==null||e(n),r==null||r({type:"error",text:l}),{errorMessage:n,displayErrorMessage:l,userName:"",userEmail:""}}const c=(d=(E=o==null?void 0:o.data)==null?void 0:E.generateCustomerToken)==null?void 0:d.token,i=await H(c),u=i==null?void 0:i.firstName,T=i==null?void 0:i.email;if(!u||!T){const N=s.customerTokenErrorMessage,n=m??N;return e==null||e(N),r==null||r({type:"error",text:n}),{errorMessage:N,displayErrorMessage:n,userName:"",userEmail:""}}const g=await S(),f=x.includes(window.location.hostname)?"":"Secure";return document.cookie=`${$.auth_dropin_firstname}=${u}; path=/; ${g}; ${f};`,document.cookie=`${$.auth_dropin_user_token}=${c}; path=/; ${g}; ${f};`,W(c)?document.cookie=`${$.auth_dropin_admin_session}=true; path=/; ${g}; SameSite=Lax; ${f};`:C($.auth_dropin_admin_session),await U(c?i==null?void 0:i.groupUid:void 0),R.emit("authenticated",!!c),p((M=v)==null?void 0:M.SIGN_IN,{...i}),{errorMessage:"",displayErrorMessage:"",userName:u,userEmail:T}};export{Z as a,H as g};
//# sourceMappingURL=getCustomerToken.js.map
