export const DEFAULT__SIGN_IN_EMAIL_FIELD = [
    {
        customUpperCode: 'email',
        code: 'email',
        default_value: '',
        entity_type: 'CUSTOMER',
        frontend_class: 'auth-sign-in-form__form__email',
        frontend_input: 'TEXT',
        is_required: true,
        multiline_count: 1,
        sort_order: 1,
        is_unique: false,
        label: 'Email',
        options: [],
    },
];
export const DEFAULT__RESET_PASSWORD_EMAIL_FIELD = [
    {
        customUpperCode: 'email',
        code: 'email',
        default_value: '',
        entity_type: 'CUSTOMER',
        frontend_class: 'auth-reset-password-form__form__item',
        frontend_input: 'TEXT',
        is_required: true,
        is_unique: false,
        label: 'Email',
        options: [],
    },
];
export const DEFAULT_SIGN_UP_FIELDS = [
    {
        customUpperCode: 'email',
        code: 'email',
        default_value: '',
        entity_type: 'CUSTOMER',
        frontend_class: '',
        frontend_input: 'TEXT',
        is_required: true,
        is_unique: false,
        label: 'Email',
        multiline_count: 1,
        sort_order: 1,
        options: [],
    },
    {
        customUpperCode: 'firstname',
        code: 'firstname',
        default_value: '',
        entity_type: 'CUSTOMER',
        frontend_class: '',
        frontend_input: 'TEXT',
        is_required: true,
        is_unique: false,
        label: 'First name',
        multiline_count: 1,
        sort_order: 2,
        options: [],
    },
    {
        customUpperCode: 'lastname',
        code: 'lastname',
        default_value: '',
        entity_type: 'CUSTOMER',
        frontend_class: '',
        frontend_input: 'TEXT',
        is_required: false,
        is_unique: false,
        label: 'Last name',
        multiline_count: 1,
        sort_order: 3,
        options: [],
    },
];
export const DEFAULT_INPUTS_PROPS = {
    date_of_birth: '',
    dob: '',
    email: '',
    firstname: '',
    gender: '',
    is_subscribed: '',
    lastname: '',
    middlename: '',
    password: '',
    prefix: '',
    suffix: '',
    taxvat: '',
};
