/********************************************************************
 * ADOBE CONFIDENTIAL
 * __________________
 *
 *  Copyright 2026 Adobe
 *  All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 *******************************************************************/
export declare const GET_RECOMMENDATIONS_BY_UNITS_QUERY = "\n  query GetRecommendationsByUnits(\n    $selector: UnitSelector!\n    $currentSku: String\n    $cartSkus: [String]\n    $userPurchaseHistory: [PurchaseHistory]\n    $userViewHistory: [ViewHistory]\n  ) {\n    recommendationsByUnits(\n      selector: $selector\n      cartSkus: $cartSkus\n      currentSku: $currentSku\n      userPurchaseHistory: $userPurchaseHistory\n      userViewHistory: $userViewHistory\n    ) {\n      results {\n        ...RECOMMENDATION_UNIT_WITH_LABEL_FRAGMENT\n      }\n      totalResults\n    }\n  }\n\n  \n  fragment RECOMMENDATION_UNIT_WITH_LABEL_FRAGMENT on RecommendationUnit {\n    ...RECOMMENDATION_UNIT_FRAGMENT\n    label\n  }\n\n  \n  fragment RECOMMENDATION_UNIT_FRAGMENT on RecommendationUnit {\n    displayOrder\n    productsView {\n      ...PRODUCTS_VIEW_FRAGMENT\n    }\n    storefrontLabel\n    totalProducts\n    typeId\n    unitId\n    unitName\n    userError\n  }\n\n  \n  fragment PRODUCTS_VIEW_FRAGMENT on ProductView {\n    __typename\n    name\n    sku\n    queryType\n    visibility\n    inStock\n    images {\n      url\n    }\n    urlKey\n    ... on SimpleProductView {\n      price {\n        final {\n          amount {\n            currency\n            value\n          }\n        }\n      }\n    }\n    ... on ComplexProductView {\n      priceRange {\n        maximum {\n          final {\n            amount {\n              currency\n              value\n            }\n          }\n        }\n        minimum {\n          final {\n            amount {\n              currency\n              value\n            }\n          }\n        }\n      }\n    }\n  }\n\n\n\n";
export declare const GET_RECOMMENDATIONS_BY_UNITS_WITH_PRODUCT_QUERY = "\n  query GetRecommendationsByUnitsWithCurrentProduct(\n    $selector: UnitSelector!\n    $currentSku: String\n    $cartSkus: [String]\n    $userPurchaseHistory: [PurchaseHistory]\n    $userViewHistory: [ViewHistory]\n    $currentProduct: CurrentProductInput\n  ) {\n    recommendationsByUnits(\n      selector: $selector\n      cartSkus: $cartSkus\n      currentSku: $currentSku\n      userPurchaseHistory: $userPurchaseHistory\n      userViewHistory: $userViewHistory\n      currentProduct: $currentProduct\n    ) {\n      results {\n        ...RECOMMENDATION_UNIT_WITH_LABEL_FRAGMENT\n      }\n      totalResults\n    }\n  }\n\n  \n  fragment RECOMMENDATION_UNIT_WITH_LABEL_FRAGMENT on RecommendationUnit {\n    ...RECOMMENDATION_UNIT_FRAGMENT\n    label\n  }\n\n  \n  fragment RECOMMENDATION_UNIT_FRAGMENT on RecommendationUnit {\n    displayOrder\n    productsView {\n      ...PRODUCTS_VIEW_FRAGMENT\n    }\n    storefrontLabel\n    totalProducts\n    typeId\n    unitId\n    unitName\n    userError\n  }\n\n  \n  fragment PRODUCTS_VIEW_FRAGMENT on ProductView {\n    __typename\n    name\n    sku\n    queryType\n    visibility\n    inStock\n    images {\n      url\n    }\n    urlKey\n    ... on SimpleProductView {\n      price {\n        final {\n          amount {\n            currency\n            value\n          }\n        }\n      }\n    }\n    ... on ComplexProductView {\n      priceRange {\n        maximum {\n          final {\n            amount {\n              currency\n              value\n            }\n          }\n        }\n        minimum {\n          final {\n            amount {\n              currency\n              value\n            }\n          }\n        }\n      }\n    }\n  }\n\n\n\n";
