/*! Copyright 2026 Adobe
All Rights Reserved. */
import{c as S,i as G}from"./chunks/initialize.js";import{f as m,h as p}from"./chunks/network-error.js";import{g as P,r as D,s as H,a as L,b as v}from"./chunks/network-error.js";import{f as M}from"./chunks/fetchUserPermissions.js";import{a as w}from"./chunks/acceptCompanyInvitation.js";import{a as Q,i as Y}from"./chunks/isCompanyUser.js";import{a as K,g as q,i as z,u as j}from"./chunks/unassignChildCompany.js";import{c as V,g as W}from"./chunks/getCustomerCompany.js";import{D as Z,S as $,c as ee,g as ae}from"./chunks/createCompany.js";import{c as te,d as oe,a as ne,g as se,b as me,u as ie}from"./chunks/updateCompanyTeam.js";import{c as ce,g as le,i as Ce,a as de,u as ye}from"./chunks/updateCompanyUserStatus.js";import{d as ue,g as ge}from"./chunks/getCompanyUsers.js";import{g as he,u as Re}from"./chunks/updateCompany.js";import{a as Te,g as Ue}from"./chunks/getCompanyCreditHistory.js";import{g as xe,v as _e}from"./chunks/validateCompanyEmail.js";import{G as c,t as l}from"./chunks/isCompanyRoleNameAvailable.js";import{c as Se,d as Ge,a as Ie,g as Pe,i as De,u as He}from"./chunks/isCompanyRoleNameAvailable.js";import{f as C}from"./chunks/company-permissions.js";import"@dropins/tools/lib.js";import"@dropins/tools/fetch-graphql.js";import"@dropins/tools/event-bus.js";import"./chunks/fetch-error.js";const d=`
 query CHECK_COMPANY_CREDIT_ENABLED {
   storeConfig{
     company_credit_enabled
   }
  }
`,T=async()=>{var e,a,o;try{const r=await m(d,{method:"GET",cache:"no-cache"});return(e=r.errors)!=null&&e.length?{creditEnabled:!1,error:"Unable to check company credit configuration"}:((o=(a=r.data)==null?void 0:a.storeConfig)==null?void 0:o.company_credit_enabled)===!0?{creditEnabled:!0}:{creditEnabled:!1,error:"Company credit is not enabled in store configuration"}}catch{return{creditEnabled:!1,error:"Company credit functionality not available"}}};var y=(e=>(e.ALLOCATION="ALLOCATION",e.UPDATE="UPDATE",e.PURCHASE="PURCHASE",e.REIMBURSEMENT="REIMBURSEMENT",e))(y||{});const U=async e=>{try{const a=await m(c,{variables:e,method:"GET",cache:"no-cache"});return l(a)}catch(a){return p(a)}},b=e=>C(e),x=(e,a)=>{const o=new Set(a),r=t=>{var s;const n=((s=t.children)==null?void 0:s.map(r).filter(i=>i!==null))||[];return o.has(t.id)||n.length>0?{...t,children:n}:null};return e.map(r).filter(t=>t!==null)};export{y as CompanyCreditOperationType,Z as DEFAULT_COUNTRY,$ as STORE_CONFIG_DEFAULTS,w as acceptCompanyInvitation,Q as allowCompanyRegistration,K as assignChildCompany,x as buildPermissionTree,T as checkCompanyCreditEnabled,V as companyEnabled,S as config,ee as createCompany,Se as createCompanyRole,te as createCompanyTeam,ce as createCompanyUser,Ge as deleteCompanyRole,oe as deleteCompanyTeam,ue as deleteCompanyUser,m as fetchGraphQl,M as fetchUserPermissions,b as flattenPermissionIds,he as getCompany,Ie as getCompanyAclResources,Te as getCompanyCredit,Ue as getCompanyCreditHistory,q as getCompanyHierarchy,U as getCompanyRole,Pe as getCompanyRoles,ne as getCompanyStructure,se as getCompanyTeam,le as getCompanyUser,ge as getCompanyUsers,P as getConfig,xe as getCountries,W as getCustomerCompany,ae as getStoreConfig,G as initialize,z as isCompanyAdmin,De as isCompanyRoleNameAvailable,Y as isCompanyUser,Ce as isCompanyUserEmailAvailable,D as removeFetchGraphQlHeader,H as setEndpoint,L as setFetchGraphQlHeader,v as setFetchGraphQlHeaders,j as unassignChildCompany,Re as updateCompany,He as updateCompanyRole,me as updateCompanyStructure,ie as updateCompanyTeam,de as updateCompanyUser,ye as updateCompanyUserStatus,_e as validateCompanyEmail};
//# sourceMappingURL=api.js.map
