name: Cypress E2E B2B SaaS Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
env:
  IS_PROD_RELEASE: ${{ github.base_ref == 'b2b-integration' }}
jobs:
  cypress-b2b-saas-groups:
    uses: ./.github/workflows/_b2b-e2e-base.yaml
    with:
      config-file: cypress.b2b.saas.config.js
      grep-tags: '@B2BSaas'
      url: ${{ env.IS_PROD_RELEASE == 'true' && 'https://main--boilerplate-b2b-accs-prod--adobe-commerce.aem.live' || 'https://main--boilerplate-b2b-accs--adobe-commerce.aem.live' }}
      graphql-endpoint: ${{ env.IS_PROD_RELEASE == 'true' && 'https://na1.api.commerce.adobe.com/MYAtJvyuQfnr4nW37jbfp1/graphql' || 'https://na1-sandbox.api.commerce.adobe.com/LwndYQs37CvkUQk9WEmNkz/graphql' }}
      is-prod-release: ${{ env.IS_PROD_RELEASE == 'true' }}
      is-aco: false
    secrets:
      AEM_ASSETS_PRIVATE_USER: ${{ secrets.AEM_ASSETS_PRIVATE_USER }}
      CYPRESS_API_ENDPOINT: ${{ secrets.CYPRESS_API_ENDPOINT }}
      CYPRESS_API_ENDPOINT_PROD: ${{ secrets.CYPRESS_API_ENDPOINT_PROD }}
      CYPRESS_IMS_CLIENT_ID: ${{ secrets.CYPRESS_IMS_CLIENT_ID }}
      CYPRESS_IMS_ORG_ID: ${{ secrets.CYPRESS_IMS_ORG_ID }}
      CYPRESS_IMS_CLIENT_SECRET: ${{ secrets.CYPRESS_IMS_CLIENT_SECRET }}

  cypress-b2b-saas-run:
    if: always()
    needs: cypress-b2b-saas-groups
    runs-on: ubuntu-latest
    steps:
      - name: Check matrix result
        run: |
          if [ "${{ needs.cypress-b2b-saas-groups.result }}" != "success" ]; then
            echo "One or more test groups failed: ${{ needs.cypress-b2b-saas-groups.result }}"
            exit 1
          fi
